### ISSUE TITLE
Kafka truststore should be optional

### ISSUE THREAD

**Issue by dajudge** [dajudge/kafkaproxy#37]
Contrary to the documentation, the truststore used for validating kafka server certificates is not optional.

When `KAFKAPROXY_KAFKA_SSL_ENABLED` is set to `true` and `KAFKAPROXY_KAFKA_SSL_TRUSTSTORE_LOCATION` is not set, then the built-in truststore (taken from JDK during native compile) should be used. Right now an exception is raised instead.

Originally raised in #31

**Comment by dajudge** [comment]
Would you mind giving 0.0.16 a spin and give me feedback if it solves the issue for you?

**Comment by jhovell** [comment]
Yes @dajudge 0.0.16 works great with Kafka 2.8 and SSL enabled. Thanks so much!
